### ISSUE TITLE
[RFC] Add exception for animated GIF

### ISSUE THREAD

**Issue by zomars** [cdowdy/boltbetterthumbs#36]
Is it possible? I want to to use this extension for a client and they make heavy use of animated gifs. Since they upload all the media, a condition to bypass an animated GIF to be processed by Glide would be a nice-have.

**Comment by cdowdy** [comment]
@zomars as in process / crop / all that jazz a regular non animated gif but skip over animated gifs?  

Or do you mean you want to use betterthumbs ( and glide) to serve animated gifs but don't use anything from glide for animated gifs?

**Comment by zomars** [comment]
Skip animated gifs processing at all maybe? I know it’s a hassle to resize and crop animated gifs so an exception to all processing would be my go to option here. I’m open to suggestions :)

**Comment by cdowdy** [comment]
can I ask why use betterthumbs for animated gifs if you aren't going to use any of the glide transformations?  

Even if you use the single image output you might be better off using bolt's image filter - that way it wont have to hit PHP on the request - side note Glide is changing how they handle modifications and serving for Glide v 2.0 and will serve images straight from disk/memory after modifications so thats awesome haha. 

I ask these things because I'm trying to map out in my head the best way to accomplish this :) I can put a method in to check for animations but I haven't tested it and don't know if it'll be bad for perf...

**Comment by zomars** [comment]
My case scenario is that the client upload thumbnails for their blog entries, but sometimes that thumbnail is animated gif. My initial reaction was to use the imageinfo function and check for a gif file extension and pass it to a normal img tag, but that would leave the non animated gifs out as well.

**Comment by cdowdy** [comment]
Ok I've got it now.. You've built templates and use betterthumbs.. So they (the editor/client) don't have control over whats in the template to output the image (nor should they)- thats me being a derp and not thinking as and end user haha my fault.  

So here is what I am thinking.. let me know if this is good so far:  

check the image if its an animated gif.  
if it is animated then just serve the image from disk like the `use_original` config option.  

```twig  
{{ bthumb( record.image, 'namedConfig') }}  
```  
if its animated it will produce:  

```html  
<img src="/files/record.image.gif"
    alt="alt text">   
```  

I used the single output here since if we use the regular ``{{ img() }}`` tag we'd have to fall back I guess if it's an animated gif to a regular non responsive image tag since any modifications done through glide (and by turn Intervention) will strip animation. 

This though means every image needs to be read or mime type checked - unless something more cleverl comes along. So i'll have to play with this a bit and make sure it doesn't degrade anything too bad.

**Comment by cdowdy** [comment]
@zomars ok I've pushed a few things and Im going to merge them with master so they should be available in a bit.  

I only focused on the ``img()`` and ``bthumb()`` functions right now since I'm not fully sure how much impact its going to have. But animated gifs should now pass through! 

Let me know if you run into any bugs! Thanks!

**Comment by zomars** [comment]
Thanks! Will check it ASAP.
