### ISSUE TITLE
path to docs and files in the backend

### ISSUE THREAD

**Issue by jemont** [cdowdy/boltbetterthumbs#44]
hi,
on bolt 3.3(.2) the pass to the backend link docs and files is 'extensions' and not 'extend'
results in a 404 error 
the path to extend still works but bolt opens extenstions

in the docs is a little typo 
for the lazyload example you missed the closing round parentheses ')'

**Comment by cdowdy** [comment]
Well that is an unexpected change in a minor version of bolt. Thanks for the heads up @jemont ! And thanks for the code example bug lol I always miss something like that! Thanks! 

For my future reference this is the relevant bolt change https://github.com/bolt/bolt/pull/6156 and I could have sworn they were using semver and a 3.2 --> 3.3 would be a minor version change that's backwards compatible and clearly this change to bolt core isn't backwards compatible 😞

**Comment by jemont** [comment]
hi, asking here since this is not an issue
is there a way to make thumbs permanent and not be deleted after a year
maybe in the named configuration group?

**Comment by cdowdy** [comment]
> is there a way to make thumbs permanent and not be deleted after a year
maybe in the named configuration group?  

Through the betterthumbs configuration no.. The 1 year expiration comes from Glide - specifically https://github.com/thephpleague/glide/blob/8077f529a07ded3eed6c5dcf7f688249b626ddf3/src/Server.php#L463-L479 and I don't see any place to over ride that.  

In Glide 2.0 (currently being worked on) You'll be able to set the expires differently since the file structure and how the modifications are used are different.

**Comment by jemont** [comment]
ok thanks,
by the way using `data-sizes="auto"`in lazyload images, doesn't load bigger images when you switch from portrait to landscape. withaout `data-sizes="auto"` it does

**Comment by cdowdy** [comment]
> by the way using data-sizes="auto"in lazyload images, doesn't load bigger images when you switch from portrait to landscape. withaout data-sizes="auto" it does

ok you'll have to head over to lazysizes repo (https://github.com/aFarkas/lazysizes) and see if that's expected behavior and make sure you're using the width descriptor and have the recommended markup patterns shown there

**Comment by cdowdy** [comment]
This is going to take some time unfortunately.... I can't just "change" the back end route since I have to have a bolt 3.3 install and they changed how extensions are loaded and in turn how you have to develop them so I can't just open up my old development environment and push this really small change for the back end route. I have to setup up my development environment again and in turn all the other extensions I have.   


https://github.com/bolt/bolt/pull/6156

**Comment by cdowdy** [comment]
Bolt's  compare method is wonky and gives the wrong result for bolt < 3.3  

This: https://github.com/cdowdy/boltbetterthumbs/blob/8dd5a8545f07fb82508df07d7a92f8baad7bbb76/src/BetterThumbsExtension.php#L904-L918  

Is wrong for bolt 3.2.x series and probably lower
